package com.aicoinassist.batch.domain.report.enumtype;

public enum AnalysisRiskFactorType {
    RSI_OVERHEATING,
    RSI_COMPRESSION,
    BAND_EXTENSION,
    ELEVATED_VOLATILITY,
    FUNDING_SKEW,
    BASIS_EXPANSION,
    OPEN_INTEREST_CROWDING,
    SENTIMENT_GREED_EXTREME,
    SENTIMENT_FEAR_EXTREME,
    ONCHAIN_ACTIVITY_CONTRACTION,
    MOMENTUM_TRANSITION,
    MACRO_VOLATILITY
}
